Repository Venomalia/UniversalDynamicInput, pull requests merged in 2022-07, with the labels that each got.

#94 Punch Out Button 1 Fix
  Punch Out/UniversalDIT_Flat.json
Labels: enhancement

#87 add Fatal Frame IV
  Fatal Frame IV/GameID/R4Z.txt
  Fatal Frame IV/UniversalDIT_Flat.json
  Fatal Frame IV/UniversalDIT_Flat_Pressed.json
  Fatal Frame IV/tex1_182x44_6ef002508d8078cd_6.png
  Fatal Frame IV/tex1_18x24_c14174dcc671fd40_5.png
  Fatal Frame IV/tex1_20x20_0c561af837804378_5.png
  Fatal Frame IV/tex1_20x20_3783437993f99c7b_5.png
  Fatal Frame IV/tex1_20x24_25653608560abd6e_5.png
  Fatal Frame IV/tex1_20x30_24f933e1f12ead14_5.png
  Fatal Frame IV/tex1_22x20_7a8637e25a7b8d27_5.png
  Fatal Frame IV/tex1_24x24_04eb06f87597b35b_6.png
  Fatal Frame IV/tex1_24x24_f37bcb090147f41e_5.png
  Fatal Frame IV/tex1_52x64_7c02c9a7f8509e92_6.png
  Fatal Frame IV/unuse/Originals/tex1_160x192_2700664b1f5b21b4_5.png
  Fatal Frame IV/unuse/Originals/tex1_182x44_6ef002508d8078cd_6.png
  Fatal Frame IV/unuse/Originals/tex1_18x24_c14174dcc671fd40_5.png
  Fatal Frame IV/unuse/Originals/tex1_20x20_0c561af837804378_5.png
  Fatal Frame IV/unuse/Originals/tex1_20x20_3783437993f99c7b_5.png
  Fatal Frame IV/unuse/Originals/tex1_20x24_25653608560abd6e_5.png
  Fatal Frame IV/unuse/Originals/tex1_20x30_24f933e1f12ead14_5.png
  Fatal Frame IV/unuse/Originals/tex1_22x20_7a8637e25a7b8d27_5.png
  Fatal Frame IV/unuse/Originals/tex1_24x24_04eb06f87597b35b_6.png
  Fatal Frame IV/unuse/Originals/tex1_24x24_f37bcb090147f41e_5.png
  Fatal Frame IV/unuse/Originals/tex1_256x256_08634972eab66bc4_3.png
  Fatal Frame IV/unuse/Originals/tex1_256x256_7e16b6bcf2d9220e_3.png
  Fatal Frame IV/unuse/Originals/tex1_256x256_8a110d130e173eb1_3.png
  Fatal Frame IV/unuse/Originals/tex1_256x256_ee886f8c1453d832_3.png
  Fatal Frame IV/unuse/Originals/tex1_256x256_fa4e991f089878dd_3.png
  Fatal Frame IV/unuse/Originals/tex1_52x64_7c02c9a7f8509e92_6.png
Labels: Game Request

#95 add Twin USB Joystick & Pro Controller
  #Assets/UniversalDIT_Defaultstyle.json
  #Assets/UniversalDIT_Defaultstyle_Pressed.json
  #Assets/UniversalDIT_Flat.json
  #Assets/UniversalDIT_Flat_Pressed.json
  #Assets/UniversalDIT_Mirror_Defaultstyle.json
  #Assets/UniversalDIT_Mirror_Defaultstyle_Pressed.json
  #Assets/UniversalDIT_Mirror_Flat.json
  #Assets/UniversalDIT_Mirror_Flat_Pressed.json
  #Assets/UniversalDIT_Mirror_Simple-Default.json
  #Assets/UniversalDIT_Mirror_Simple-Default_EX.json
  #Assets/UniversalDIT_Mirror_Text-Default.json
  #Assets/UniversalDIT_Mirror_Text-Outlines.json
  #Assets/UniversalDIT_Simple-Default.json
  #Assets/UniversalDIT_Simple-Default_EX.json
  #Assets/UniversalDIT_Text-Default.json
  #Assets/UniversalDIT_Text-Outlines.json
Labels: Device Request

#82 Add PowerA Spectra Linux
  #Assets/UniversalDIT_Defaultstyle.json
  #Assets/UniversalDIT_Defaultstyle_Pressed.json
  #Assets/UniversalDIT_Flat.json
  #Assets/UniversalDIT_Flat_Pressed.json
  #Assets/UniversalDIT_Mirror_Defaultstyle.json
  #Assets/UniversalDIT_Mirror_Defaultstyle_Pressed.json
  #Assets/UniversalDIT_Mirror_Flat.json
  #Assets/UniversalDIT_Mirror_Flat_Pressed.json
  #Assets/UniversalDIT_Mirror_Simple-Default.json
  #Assets/UniversalDIT_Mirror_Simple-Default_EX.json
  #Assets/UniversalDIT_Mirror_Text-Default.json
  #Assets/UniversalDIT_Mirror_Text-Outlines.json
  #Assets/UniversalDIT_Simple-Default.json
  #Assets/UniversalDIT_Simple-Default_EX.json
  #Assets/UniversalDIT_Text-Default.json
  #Assets/UniversalDIT_Text-Outlines.json
Labels: Device Request

#106 Super Smash Bros Brawl add missing textures
  Super Smash Bros Brawl/UniversalDIT_Devices.json
  Super Smash Bros Brawl/UniversalDIT_Flat.json
  Super Smash Bros Brawl/tex1_40x36_900213d55eb68682_8329912412220973_9.png
  Super Smash Bros Brawl/tex1_40x36_9ceffd0f1fae7131_59a78f70a511483d_9.png
  Super Smash Bros Brawl/tex1_40x36_a1279a4bdbf60d73_7242d6aafafa1fc7_9.png
  Super Smash Bros Brawl/tex1_40x56_1d3e94694c7235ad_305cdce34716d0ef_9.png
  Super Smash Bros Brawl/tex1_40x56_2e93c63aa6655c9e_6ab6523fc9574806_9.png
  Super Smash Bros Brawl/tex1_40x56_3991c0925cc43bd7_688fec5fb12f2df4_9.png
  Super Smash Bros Brawl/tex1_40x56_c8d97ec2595b1f63_5ae4b7808cbfca63_9.png
  Super Smash Bros Brawl/tex1_48x32_926ab381d0ac088c_ec8f9b094429ea3b_9.png
  Super Smash Bros Brawl/tex1_48x32_d2d08316c010fce0_d8145c321ae28b13_9.png
  Super Smash Bros Brawl/tex1_72x56_3c8030f0d1a96f7b_553674130b524dd4_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x36_900213d55eb68682_8329912412220973_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x36_9ceffd0f1fae7131_59a78f70a511483d_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x36_a1279a4bdbf60d73_7242d6aafafa1fc7_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x56_1d3e94694c7235ad_305cdce34716d0ef_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x56_2e93c63aa6655c9e_6ab6523fc9574806_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x56_3991c0925cc43bd7_688fec5fb12f2df4_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_40x56_c8d97ec2595b1f63_5ae4b7808cbfca63_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_48x32_926ab381d0ac088c_ec8f9b094429ea3b_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_48x32_d2d08316c010fce0_d8145c321ae28b13_9.png
  Super Smash Bros Brawl/unuse/Originals/tex1_72x56_3c8030f0d1a96f7b_553674130b524dd4_9.png
Labels: Missing textures
